services:
  postgres:
    image: postgres:17
    container_name: splitwise_postgres
    restart: always

    environment:
      POSTGRES_DB: splitwise_db
      POSTGRES_USER: splitwise_user
      POSTGRES_PASSWORD: splitwise_password

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: